---
general:
  camera_name:   "zed2i"
  camera_model:  "zed2i"
  grab_resolution: "HD720"
  grab_frame_rate: 30
  gpu_id: 0
  async_grab_camera_recovery: true
depth:
  depth_mode: "NEURAL"
  depth_stabilization: 1
  min_depth: 0.3
  max_depth: 10.0
  openni_depth_mode: false
pos_tracking:
  pos_tracking_enabled: true
  imu_fusion: true
  set_gravity_as_origin: true
  publish_tf: true
  publish_map_tf: true
  publish_imu_tf: true
  area_memory_db_path: ""
  save_area_memory_on_closing: true
  enable_localization_only: false
  reset_odom_with_loop_closure: true
  floor_alignment: false
  two_d_mode: false
  path_pub_rate: 1.0
  path_max_count: 500
  initial_base_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
mapping:
  mapping_enabled: false
sensors:
  sensors_image_sync: false
  sensors_pub_rate: 400.0
object_detection:
  od_enabled: false
body_tracking:
  bt_enabled: false
